source 'https://rubygems.org'

gem 'github-pages', group: :jekyll_plugins
gem 'activesupport', '4.2.10'
gem 'github-pages-health-check', '1.16.1'
#gem 'github-pages', '197'
gem 'html-pipeline', '2.10.0'
gem 'jekyll-avatar', '0.6.0'
gem 'jekyll-coffeescript', '1.1.1'
gem 'jekyll-default-layout', '0.1.4'
gem 'jekyll-feed', '0.11.0'
gem 'jekyll-gist', '1.5.0'
gem 'jekyll-github-metadata', '2.12.1'
gem 'jekyll-mentions', '1.4.1'
gem 'jekyll-optional-front-matter', '0.3.0'
gem 'jekyll-paginate', '1.1.0'
gem 'jekyll-readme-index', '0.2.0'
gem 'jekyll-redirect-from', '0.14.0'
gem 'jekyll-relative-links', '0.6.0'
gem 'jekyll-sass-converter', '1.5.2'
gem 'jekyll-seo-tag', '2.5.0'
gem 'jekyll-sitemap', '1.2.0'
gem 'jekyll-swiss', '0.4.0'
gem 'jekyll-theme-architect', '0.1.1'
gem 'jekyll-theme-cayman', '0.1.1'
gem 'jekyll-theme-dinky', '0.1.1'
gem 'jekyll-theme-hacker', '0.1.1'
gem 'jekyll-theme-leap-day', '0.1.1'
gem 'jekyll-theme-merlot', '0.1.1'
gem 'jekyll-theme-midnight', '0.1.1'
gem 'jekyll-theme-minimal', '0.1.1'
gem 'jekyll-theme-modernist', '0.1.1'
gem 'jekyll-theme-primer', '0.5.3'
gem 'jekyll-theme-slate', '0.1.1'
gem 'jekyll-theme-tactile', '0.1.1'
gem 'jekyll-theme-time-machine', '0.1.1'
gem 'jekyll-titles-from-headings', '0.5.1'
gem 'jemoji', '0.10.2'
gem 'kramdown', '1.17.0'
gem 'liquid', '4.0.0'
gem 'listen', '3.1.5'
gem 'minima', '2.5.0'
gem 'nokogiri', '~> 1.8.5'
gem 'rouge', '2.2.1'
gem 'safe_yaml', '1.0.5'
gem 'sass', '3.7.3'

# by Young-June Woo
#group :jekyll_plugins do
gem 'jekyll-paginate-v2', '1.9.0'
#end
